### ISSUE TITLE
Drop `jslint` reporter file

### ISSUE THREAD

**Issue by leobalter** [vistaprint/ArteJS#34]
Is there any usage of the JSHint report (in JSLint style) usage or should we drop it? I didn't find anything from the Travis CI or similar that could use it.

Actually, the report is omitting a JSHint check issue in the stdout.

https://github.com/vistaprint/ArteJS/blob/master/Gruntfile.js#L25-L26

**Comment by ilyavolodin** [comment]
I think that was originally added for Jenkings tracking for lint errors. In all honesty, I think I copied Gruntfile from another project that I was working on at that time. So I don't think reporter is used for anything.

**Comment by leobalter** [comment]
Thanks, the report file will be deleted on #35
