### ISSUE TITLE
JSHint and JSCS all source, including test files.

### ISSUE THREAD

**Issue by leobalter** [vistaprint/ArteJS#39]
Only exception is the external dependencies.

**Comment by Wilto** [comment]
1af435141f3b788289d0a01f6476560eead30f31
e67739609e027581864217b757e5bbd89d562226

All set to close?

**Comment by leobalter** [comment]
https://github.com/vistaprint/ArteJS/blob/master/Gruntfile.js#L9-L27

good to close.
