### ISSUE TITLE
References to “font-family: "curier-new"” in demo

### ISSUE THREAD

**Issue by Wilto** [vistaprint/ArteJS#53]
Assuming this is a typo and should be `Courier New`, but I wanted to check in before making any changes (making sure it isn’t testing an intentional failure state or anything).

**Comment by chriskwan** [comment]
Looks like this was a typo in the [toolbar config] (https://github.com/vistaprint/ArteJS/blob/master/src/toolbar/Configuration.js#L177) that just got referenced in the demo. It should be `Courier New`

**Comment by chriskwan** [comment]
Fixed.
