### ISSUE TITLE
Allow quick replacement of unsanctioned tags

### ISSUE THREAD

**Issue by HarminderSingh1** [vistaprint/ArteJS#9]
Tablet context menu allows appling rich text command in a browser specific way and editor doesn’t get notified when such commands are applied.  We should allow a quick replacement of such “unsanctioned” tags when getting the editor value and it should be controllable through a configuration setting.  (Checking for unsanctioned tags on every text change would be an overkill).

**Comment by chriskwan** [comment]
@HarminderSingh1 Did you already fix this?

**Comment by HarminderSingh1** [comment]
This has been fixed.
